local remap = vim.keymap.set
remap('n', '<leader>o', 'o<ESC>k', { noremap = true, silent = true })
remap('n', '<leader>O', 'O<ESC>j', { noremap = true, silent = true })
remap('n', '<F8>', ':e %<CR>', { noremap = true, silent = true })

remap({ 'n', 'v' }, 'H', '^', { noremap = true, silent = true })
remap({ 'n', 'v' }, 'L', '$', { noremap = true, silent = true })
remap({ 'n', 'v' }, 'w', 'W', { noremap = true, silent = true })
remap({ 'n', 'v' }, 'W', 'w', { noremap = true, silent = true })
remap({ 'n', 'v' }, 'e', 'E', { noremap = true, silent = true })
remap({ 'n', 'v' }, 'E', 'e', { noremap = true, silent = true })
remap({ 'n', 'v' }, 'b', 'B', { noremap = true, silent = true })
remap({ 'n', 'v' }, 'B', 'b', { noremap = true, silent = true })
remap({ 'n', 'v' }, "'", ';', { noremap = true, silent = true })
remap('n', 'Y', 'y$', { noremap = true, silent = true })
remap({ 'n', 'v' }, ';', ':', { noremap = true })
remap('i', ',', ',<c-g>u', { noremap = true, silent = true })
remap('i', '.', '.<c-g>u', { noremap = true, silent = true })
remap('i', '!', '!<c-g>u', { noremap = true, silent = true })
remap('i', '?', '?<c-g>u', { noremap = true, silent = true })
remap('n', 'n', 'nzzzv', { noremap = true, silent = true })
remap('n', 'N', 'Nzzzv', { noremap = true, silent = true })
remap('n', '<leader>j', ':m .+1<CR>==', { noremap = true, silent = true })
remap('n', '<leader>k', ':m .-2<CR>==', { noremap = true, silent = true })

remap({ 'n', 'v' }, '<A-h>', '5h', { noremap = true, silent = true })
remap({ 'n', 'v' }, '<A-j>', '5j', { noremap = true, silent = true })
remap({ 'n', 'v' }, '<A-k>', '5k', { noremap = true, silent = true })
remap({ 'n', 'v' }, '<A-l>', '5l', { noremap = true, silent = true })

remap('n', '<C-h>', '<C-w>h', { noremap = true, silent = true })
remap('n', '<C-j>', '<C-w>j', { noremap = true, silent = true })
remap('n', '<C-k>', '<C-w>k', { noremap = true, silent = true })
remap('n', '<C-l>', '<C-w>l', { noremap = true, silent = true })
remap('n', '<leader>q', '%', { noremap = true, silent = true })
remap('n', '<leader>vw', 'v%', { noremap = true, silent = true })
remap('t', '<ESC>', '<C-\\><C-n>', { noremap = true, silent = true })
remap('i', '<C-l>', '<Right>', { noremap = true, silent = true })

remap('v', '<C-c>', '"+y', { noremap = true, silent = true })
remap('n', '<A-v>', '"+p', { noremap = true, silent = true })
